/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GigsRouteImport } from './routes/gigs'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as GigsIndexRouteImport } from './routes/gigs/index'
import { Route as GigsIdRouteImport } from './routes/gigs/$id'
import { Route as TalentIndexRouteImport } from './routes/talent/index'
import { Route as TalentIdRouteImport } from './routes/talent/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsRoute = GigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GigsRoute,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GigsRoute,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRoute,
} as any)
const TalentIdRoute = TalentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TalentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gigs': typeof GigsRouteWithChildren
  '/studio': typeof StudioRoute
  '/talent': typeof TalentRouteWithChildren
  '/gigs/$id': typeof GigsIdRoute
  '/talent/$id': typeof TalentIdRoute
  '/gigs/': typeof GigsIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/gigs/$id': typeof GigsIdRoute
  '/talent/$id': typeof TalentIdRoute
  '/gigs': typeof GigsIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gigs': typeof GigsRouteWithChildren
  '/studio': typeof StudioRoute
  '/talent': typeof TalentRouteWithChildren
  '/gigs/$id': typeof GigsIdRoute
  '/talent/$id': typeof TalentIdRoute
  '/gigs/': typeof GigsIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gigs'
    | '/studio'
    | '/talent'
    | '/gigs/$id'
    | '/talent/$id'
    | '/gigs/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/gigs/$id' | '/talent/$id' | '/gigs' | '/talent'
  id:
    | '__root__'
    | '/'
    | '/gigs'
    | '/studio'
    | '/talent'
    | '/gigs/$id'
    | '/talent/$id'
    | '/gigs/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GigsRoute: typeof GigsRouteWithChildren
  StudioRoute: typeof StudioRoute
  TalentRoute: typeof TalentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs': {
      id: '/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof GigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof GigsRoute
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof GigsRoute
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRoute
    }
    '/talent/$id': {
      id: '/talent/$id'
      path: '/$id'
      fullPath: '/talent/$id'
      preLoaderRoute: typeof TalentIdRouteImport
      parentRoute: typeof TalentRoute
    }
  }
}

interface GigsRouteChildren {
  GigsIdRoute: typeof GigsIdRoute
  GigsIndexRoute: typeof GigsIndexRoute
}

const GigsRouteChildren: GigsRouteChildren = {
  GigsIdRoute: GigsIdRoute,
  GigsIndexRoute: GigsIndexRoute,
}

const GigsRouteWithChildren = GigsRoute._addFileChildren(GigsRouteChildren)

interface TalentRouteChildren {
  TalentIdRoute: typeof TalentIdRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentIdRoute: TalentIdRoute,
  TalentIndexRoute: TalentIndexRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GigsRoute: GigsRouteWithChildren,
  StudioRoute: StudioRoute,
  TalentRoute: TalentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
